apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd
  labels:
    app: ci-cd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd
  template:
    metadata:
      labels:
        app: ci-cd
    spec:
      containers:
      - name: ci-cd
        image: {{IMAGE}}
        ports:
        - containerPort: 8000
